# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\menaceDesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(156, 152)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(156, 152))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("corner.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Left = QtGui.QVBoxLayout()
        self.Left.setSpacing(0)
        self.Left.setObjectName(_fromUtf8("Left"))
        self.UL = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UL.sizePolicy().hasHeightForWidth())
        self.UL.setSizePolicy(sizePolicy)
        self.UL.setMinimumSize(QtCore.QSize(50, 50))
        self.UL.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.UL.setFont(font)
        self.UL.setObjectName(_fromUtf8("UL"))
        self.Left.addWidget(self.UL)
        self.ML = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ML.sizePolicy().hasHeightForWidth())
        self.ML.setSizePolicy(sizePolicy)
        self.ML.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.ML.setFont(font)
        self.ML.setText(_fromUtf8(""))
        self.ML.setObjectName(_fromUtf8("ML"))
        self.Left.addWidget(self.ML)
        self.LL = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LL.sizePolicy().hasHeightForWidth())
        self.LL.setSizePolicy(sizePolicy)
        self.LL.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.LL.setFont(font)
        self.LL.setText(_fromUtf8(""))
        self.LL.setObjectName(_fromUtf8("LL"))
        self.Left.addWidget(self.LL)
        self.horizontalLayout.addLayout(self.Left)
        self.Middle = QtGui.QVBoxLayout()
        self.Middle.setSpacing(0)
        self.Middle.setObjectName(_fromUtf8("Middle"))
        self.UM = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UM.sizePolicy().hasHeightForWidth())
        self.UM.setSizePolicy(sizePolicy)
        self.UM.setMinimumSize(QtCore.QSize(50, 50))
        self.UM.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.UM.setFont(font)
        self.UM.setText(_fromUtf8(""))
        self.UM.setObjectName(_fromUtf8("UM"))
        self.Middle.addWidget(self.UM)
        self.MM = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MM.sizePolicy().hasHeightForWidth())
        self.MM.setSizePolicy(sizePolicy)
        self.MM.setMinimumSize(QtCore.QSize(50, 50))
        self.MM.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.MM.setFont(font)
        self.MM.setText(_fromUtf8(""))
        self.MM.setObjectName(_fromUtf8("MM"))
        self.Middle.addWidget(self.MM)
        self.LM = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LM.sizePolicy().hasHeightForWidth())
        self.LM.setSizePolicy(sizePolicy)
        self.LM.setMinimumSize(QtCore.QSize(50, 50))
        self.LM.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.LM.setFont(font)
        self.LM.setText(_fromUtf8(""))
        self.LM.setObjectName(_fromUtf8("LM"))
        self.Middle.addWidget(self.LM)
        self.horizontalLayout.addLayout(self.Middle)
        self.Right = QtGui.QVBoxLayout()
        self.Right.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.Right.setSpacing(0)
        self.Right.setObjectName(_fromUtf8("Right"))
        self.UR = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UR.sizePolicy().hasHeightForWidth())
        self.UR.setSizePolicy(sizePolicy)
        self.UR.setMinimumSize(QtCore.QSize(50, 50))
        self.UR.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.UR.setFont(font)
        self.UR.setText(_fromUtf8(""))
        self.UR.setObjectName(_fromUtf8("UR"))
        self.Right.addWidget(self.UR)
        self.MR = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MR.sizePolicy().hasHeightForWidth())
        self.MR.setSizePolicy(sizePolicy)
        self.MR.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.MR.setFont(font)
        self.MR.setText(_fromUtf8(""))
        self.MR.setObjectName(_fromUtf8("MR"))
        self.Right.addWidget(self.MR)
        self.LR = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LR.sizePolicy().hasHeightForWidth())
        self.LR.setSizePolicy(sizePolicy)
        self.LR.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.LR.setFont(font)
        self.LR.setText(_fromUtf8(""))
        self.LR.setObjectName(_fromUtf8("LR"))
        self.Right.addWidget(self.LR)
        self.horizontalLayout.addLayout(self.Right)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Menace", None))
        self.UL.setText(_translate("MainWindow", "X", None))

